### ISSUE TITLE
Cant get it to run on Wemos D1 mini

### ISSUE THREAD

**Issue by MMSNord** [idolpx/meatloaf-archived#14]
NO proplem building and programing device.
But when trying to use serial monitor to troubleshoot, i dont recive any readeble information only random charakters or *.
Could be something i have missed but it is not easy to find information about how this is suppose to work.

**Comment by idolpx** [comment]
The default baud rate is 2400.
Enter the following in the terminal to change the baud rate.
```
CTRL+T
B
2400
```

Once that is done you should be able to enter AT commands.
Then you can change the default baud rate to a higher speed and save that.
Then you should be good.
