### ISSUE TITLE
Build pipeline

### ISSUE THREAD

**Issue by kpishere** [idolpx/meatloaf-archived#15]
Great project!

I'm imagining being able to open a telnet session with some server, using build tools that write my compiled PRG file to a target folder location, and then use LOAD"host:myprog.prg",X,1 to load and run.  That would be awesome!

Maybe not even enter a terminal program?  More like a DOS wedge that sends/receives to that telnet session that is kept open bey the ESP8266/ESP32?  That would be cool.

The alternative is memory and CPU expander cartridges which just don't seem feasible anymore.   Let the C64 have it's dignity and communicate via its multi-channel serial port on its own terms!

**Comment by ssuukk** [comment]
That's already possible.

**Comment by idolpx** [comment]
Yes... you can build your program on the pc then save to Meatloaf via WebDAV.
Then on Meatloaf you just LOAD"FILE.PRG",X,1 and you are good.
